= Data4Life FHIR Helper SDK
:link-repository: https://github.com/d4l-data4life/hc-fhir-helper-sdk-kmp
:project-version: 1.9.0
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]


++++
<div align="center">
    <p><!-- PROJECT LOGO -->
        <a href="https://github.com/d4l-data4life/hc-fhir-helper-sdk-kmp">
            <img src="assets/images/d4l-logo.svg" width="150"/>
        </a>
    </p>
    <p><!-- PROJECT TITLE -->
        <h3>Data4Life FHIR Helper SDK</h3>
    </p>
    <p><!-- PROJECT DESCRIPTION -->
        Provides builder and extension to create and interact with FHIR objects
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="README.adoc"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/d4l-data4life/hc-fhir-helper-sdk-kmp/issues">Report Bug</a>
        ·
        <a href="https://github.com/d4l-data4life/hc-fhir-helper-sdk-kmp/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them -->
        <a href="https://github.com/d4l-data4life/hc-fhir-helper-sdk-kmp/releases">
            <img src="assets/images/badge-release-latest.svg" alt="Latest release"/>
        </a>
        <a href="https://github.com/d4l-data4life/hc-fhir-helper-sdk-kmp/actions">
            <img src="https://github.com/d4l-data4life/hc-fhir-helper-sdk-kmp/actions/workflows/d4l-ci-latest-version.yml/badge.svg" alt="D4L CI - Latest Version"/>
        </a>
        <a>
            <img src="assets/images/badge-platform-support.svg" alt="Platform"/>
        </a>
        <a href="LICENSE">
            <img src="assets/images/badge-license.svg" alt="License"/>
        </a>
    </p>
</div>
++++

[discrete]
=== Table Of Contents
toc::[]


== About The Project

This project provides helpers that allow usage of FHIR objects within D4L without knowledge about every detail and variation that is possible working with FHIR objects.

As of now there is no shared common implementation due to the missing FHIR multiplatform SDK.
Therefore the sources are basically 1:1 in `androidMain` and `jvmMain`.

=== Features

* Builders to easily construct FHIR objects
* Kotlin Extensions that simplify FHIR object manipulation

=== Built With

* link:https://kotlinlang.org/docs/reference/mpp-intro.html[Kotlin Multiplatform]


== Getting Started

=== Requirements

* link:https://adoptopenjdk.net/[Java 11] | link:https://developer.android.com/studio/write/java8-support[Limitations of Java language features and APIs] | https://jakewharton.com/d8-library-desugaring/[Desugaring]
* link:https://kotlinlang.org/[Kotlin 1.6.10]
* Android 6.0 (API 23) to Android 11.0 (API 31)

=== Installation

Add the following maven repository url to your root build.gradle.kts:

Please take a look over at Github link:https://docs.github.com/en/packages/publishing-and-managing-packages/about-github-packages#about-tokens[aboout-github-packages#tokens] on how to generate your private token for accessing the Github Package Registry.
Add `gpr.user = {your Github username}` and `gpr.key = {private github access token}` to your `gradle.properties`

----
allprojects {
    repositories {
        ...
        maven {
            url = uri("https://maven.pkg.github.com/d4l-data4life/hc-fhir-helper-sdk-kmp")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("PACKAGE_REGISTRY_USERNAME")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("PACKAGE_REGISTRY_TOKEN")
            }
        }
    }
}
----

Your GitHub *username* and *token* needs to be stored in your global Gradle properties: `~/.gradle/gradle.properties`

NOTICE:: You need to have _read_ access to this repository and generate a https://github.com/settings/tokens/new/[personal access token] with `repo`, `write:packages` and `read:packages` scope.

----
gpr.user=github-username
gpr.key=github-token
----

=== Java

Add following dependencies to your app build.gradle.kts.

----
dependencies {
    implementation("care.data4life.hc-fhir-helper-sdk-kmp:fhir-helper-jvm:$version")
}
----


=== Android

Add following dependencies to your app build.gradle.kts.

----
dependencies {
    implementation("care.data4life.hc-fhir-helper-sdk-kmp:fhir-helper-android:$version")
}
----

== Roadmap

This project is work in progress. We are working on adding more functionality, guidelines, documentation and other improvements.

== Changelog

See link:CHANGELOG.adoc[changelog]

== Versioning

We use http://semver.org/[Semantic Versioning] as a guideline for our versioning.

Releases use this format: `{major}.{minor}.{patch}`

* Breaking changes bump `{major}` and reset `{minor}` & `{patch}`
* Backward compatible changes bump `{minor}` and reset `{patch}`
* Bug fixes bump `{patch}`

== Contributing

You want to help or share a proposal? You have a specific problem? Read the following:

* link:CODE-OF-CONDUCT.adoc[Code of conduct] for details on our code of conduct.
* link:CONTRIBUTING.adoc[Contributing] for details about how to report bugs and propose features.
* link:DEVELOPING.adoc[Developing] for details about our development process and how to build and test the project.

== Copyright and License

Copyright (c) 2021 D4L data4life gGmbH / All rights reserved. Please refer to our link:LICENSE[License] for further details.
